export const CountryCodesData = [
  { code: "+1", name: "Canada", flag: "CA" },
  { code: "+7 840", name: "Abkhazia", flag: "GE" },
  { code: "+93", name: "Afghanistan", flag: "AF" },
  { code: "+355", name: "Albania", flag: "AL" },
  { code: "+213", name: "Algeria", flag: "DZ" },
  { code: "+1 684", name: "American Samoa", flag: "AS" },
  { code: "+376", name: "Andorra", flag: "AD" },
  { code: "+244", name: "Angola", flag: "AO" },
  { code: "+1 264", name: "Anguilla", flag: "AI" },
  { code: "+1 268", name: "Antigua and Barbuda", flag: "AG" },
  { code: "+54", name: "Argentina", flag: "AR" },
  { code: "+374", name: "Armenia", flag: "AM" },
  { code: "+297", name: "Aruba", flag: "AW" },
  { code: "+247", name: "Ascension", flag: "SH" },
  { code: "+61", name: "Australia", flag: "AU" },
  { code: "+672", name: "Australian External Territories", flag: "AU" },
  { code: "+43", name: "Austria", flag: "AT" },
  { code: "+994", name: "Azerbaijan", flag: "AZ" },
  { code: "+1 242", name: "Bahamas", flag: "BS" },
  { code: "+973", name: "Bahrain", flag: "BH" },
  { code: "+880", name: "Bangladesh", flag: "BD" },
  { code: "+1 246", name: "Barbados", flag: "BB" },
  { code: "+1 268", name: "Barbuda", flag: "AG" },
  { code: "+375", name: "Belarus", flag: "BY" },
  { code: "+32", name: "Belgium", flag: "BE" },
  { code: "+501", name: "Belize", flag: "BZ" },
  { code: "+229", name: "Benin", flag: "BJ" },
  { code: "+1 441", name: "Bermuda", flag: "BM" },
  { code: "+975", name: "Bhutan", flag: "BT" },
  { code: "+591", name: "Bolivia", flag: "BO" },
  { code: "+387", name: "Bosnia and Herzegovina", flag: "BA" },
  { code: "+267", name: "Botswana", flag: "BW" },
  { code: "+55", name: "Brazil", flag: "BR" },
  { code: "+246", name: "British Indian Ocean Territory", flag: "IO" },
  { code: "+1 284", name: "British Virgin Islands", flag: "VG" },
  { code: "+673", name: "Brunei", flag: "BN" },
  { code: "+359", name: "Bulgaria", flag: "BG" },
  { code: "+226", name: "Burkina Faso", flag: "BF" },
  { code: "+257", name: "Burundi", flag: "BI" },
  { code: "+855", name: "Cambodia", flag: "KH" },
  { code: "+237", name: "Cameroon", flag: "CM" },
  { code: "+238", name: "Cape Verde", flag: "CV" },
  { code: "+345", name: "Cayman Islands", flag: "KY" },
  { code: "+236", name: "Central African Republic", flag: "CF" },
  { code: "+235", name: "Chad", flag: "TD" },
  { code: "+56", name: "Chile", flag: "CL" },
  { code: "+86", name: "China", flag: "CN" },
  { code: "+61", name: "Christmas Island", flag: "CX" },
  { code: "+61", name: "Cocos-Keeling Islands", flag: "CC" },
  { code: "+57", name: "Colombia", flag: "CO" },
  { code: "+269", name: "Comoros", flag: "KM" },
  { code: "+242", name: "Congo", flag: "CG" },
  { code: "+243", name: "Congo, Dem. Rep. of (Zaire)", flag: "CD" },
  { code: "+682", name: "Cook Islands", flag: "CK" },
  { code: "+506", name: "Costa Rica", flag: "CR" },
  { code: "+385", name: "Croatia", flag: "HR" },
  { code: "+53", name: "Cuba", flag: "CU" },
  { code: "+599", name: "Curacao", flag: "CW" },
  { code: "+537", name: "Cyprus", flag: "CY" },
  { code: "+420", name: "Czech Republic", flag: "CZ" },
  { code: "+45", name: "Denmark", flag: "DK" },
  { code: "+253", name: "Djibouti", flag: "DJ" },
  { code: "+1 767", name: "Dominica", flag: "DM" },
  { code: "+1 809", name: "Dominican Republic", flag: "DO" },
  { code: "+593", name: "Ecuador", flag: "EC" },
  { code: "+20", name: "Egypt", flag: "EG" },
  { code: "+503", name: "El Salvador", flag: "SV" },
  { code: "+240", name: "Equatorial Guinea", flag: "GQ" },
  { code: "+291", name: "Eritrea", flag: "ER" },
  { code: "+372", name: "Estonia", flag: "EE" },
  { code: "+251", name: "Ethiopia", flag: "ET" },
  { code: "+500", name: "Falkland Islands", flag: "FK" },
  { code: "+298", name: "Faroe Islands", flag: "FO" },
  { code: "+679", name: "Fiji", flag: "FJ" },
  { code: "+358", name: "Finland", flag: "FI" },
  { code: "+33", name: "France", flag: "FR" },
  { code: "+594", name: "French Guiana", flag: "GF" },
  { code: "+689", name: "French Polynesia", flag: "PF" },
  { code: "+241", name: "Gabon", flag: "GA" },
  { code: "+220", name: "Gambia", flag: "GM" },
  { code: "+995", name: "Georgia", flag: "GE" },
  { code: "+49", name: "Germany", flag: "DE" },
  { code: "+233", name: "Ghana", flag: "GH" },
  { code: "+350", name: "Gibraltar", flag: "GI" },
  { code: "+30", name: "Greece", flag: "GR" },
  { code: "+299", name: "Greenland", flag: "GL" },
  { code: "+1 473", name: "Grenada", flag: "GD" },
  { code: "+590", name: "Guadeloupe", flag: "GP" },
  { code: "+1 671", name: "Guam", flag: "GU" },
  { code: "+502", name: "Guatemala", flag: "GT" },
  { code: "+224", name: "Guinea", flag: "GN" },
  { code: "+245", name: "Guinea-Bissau", flag: "GW" },
  { code: "+592", name: "Guyana", flag: "GY" },
  { code: "+509", name: "Haiti", flag: "HT" },
  { code: "+504", name: "Honduras", flag: "HN" },
  { code: "+852", name: "Hong Kong SAR China", flag: "HK" },
  { code: "+36", name: "Hungary", flag: "HU" },
  { code: "+354", name: "Iceland", flag: "IS" },
  { code: "+91", name: "India", flag: "IN" },
  { code: "+62", name: "Indonesia", flag: "ID" },
  { code: "+98", name: "Iran", flag: "IR" },
  { code: "+964", name: "Iraq", flag: "IQ" },
  { code: "+353", name: "Ireland", flag: "IE" },
  { code: "+972", name: "Israel", flag: "IL" },
  { code: "+39", name: "Italy", flag: "IT" },
  { code: "+225", name: "Ivory Coast", flag: "CI" },
  { code: "+1 876", name: "Jamaica", flag: "JM" },
  { code: "+81", name: "Japan", flag: "JP" },
  { code: "+962", name: "Jordan", flag: "JO" },
  { code: "+7", name: "Kazakhstan", flag: "KZ" },
  { code: "+254", name: "Kenya", flag: "KE" },
  { code: "+686", name: "Kiribati", flag: "KI" },
  { code: "+965", name: "Kuwait", flag: "KW" },
  { code: "+996", name: "Kyrgyzstan", flag: "KG" },
  { code: "+856", name: "Laos", flag: "LA" },
  { code: "+371", name: "Latvia", flag: "LV" },
  { code: "+961", name: "Lebanon", flag: "LB" },
  { code: "+266", name: "Lesotho", flag: "LS" },
  { code: "+231", name: "Liberia", flag: "LR" },
  { code: "+218", name: "Libya", flag: "LY" },
  { code: "+423", name: "Liechtenstein", flag: "LI" },
  { code: "+370", name: "Lithuania", flag: "LT" },
  { code: "+352", name: "Luxembourg", flag: "LU" },
  { code: "+853", name: "Macau SAR China", flag: "MO" },
  { code: "+389", name: "Macedonia", flag: "MK" },
  { code: "+261", name: "Madagascar", flag: "MG" },
  { code: "+265", name: "Malawi", flag: "MW" },
  { code: "+60", name: "Malaysia", flag: "MY" },
  { code: "+960", name: "Maldives", flag: "MV" },
  { code: "+223", name: "Mali", flag: "ML" },
  { code: "+356", name: "Malta", flag: "MT" },
  { code: "+692", name: "Marshall Islands", flag: "MH" },
  { code: "+596", name: "Martinique", flag: "MQ" },
  { code: "+222", name: "Mauritania", flag: "MR" },
  { code: "+230", name: "Mauritius", flag: "MU" },
  { code: "+262", name: "Mayotte", flag: "YT" },
  { code: "+52", name: "Mexico", flag: "MX" },
  { code: "+691", name: "Micronesia", flag: "FM" },
  { code: "+373", name: "Moldova", flag: "MD" },
  { code: "+377", name: "Monaco", flag: "MC" },
  { code: "+976", name: "Mongolia", flag: "MN" },
  { code: "+382", name: "Montenegro", flag: "ME" },
  { code: "+1664", name: "Montserrat", flag: "MS" },
  { code: "+212", name: "Morocco", flag: "MA" },
  { code: "+95", name: "Myanmar", flag: "MM" },
  { code: "+264", name: "Namibia", flag: "NA" },
  { code: "+674", name: "Nauru", flag: "NR" },
  { code: "+977", name: "Nepal", flag: "NP" },
  { code: "+31", name: "Netherlands", flag: "NL" },
  { code: "+599", name: "Netherlands Antilles", flag: "CW" },
  { code: "+687", name: "New Caledonia", flag: "NC" },
  { code: "+64", name: "New Zealand", flag: "NZ" },
  { code: "+505", name: "Nicaragua", flag: "NI" },
  { code: "+227", name: "Niger", flag: "NE" },
  { code: "+234", name: "Nigeria", flag: "NG" },
  { code: "+683", name: "Niue", flag: "NU" },
  { code: "+672", name: "Norfolk Island", flag: "NF" },
  { code: "+850", name: "North Korea", flag: "KP" },
  { code: "+1 670", name: "Northern Mariana Islands", flag: "MP" },
  { code: "+47", name: "Norway", flag: "NO" },
  { code: "+968", name: "Oman", flag: "OM" },
  { code: "+92", name: "Pakistan", flag: "PK" },
  { code: "+680", name: "Palau", flag: "PW" },
  { code: "+970", name: "Palestine", flag: "PS" },
  { code: "+507", name: "Panama", flag: "PA" },
  { code: "+675", name: "Papua New Guinea", flag: "PG" },
  { code: "+595", name: "Paraguay", flag: "PY" },
  { code: "+51", name: "Peru", flag: "PE" },
  { code: "+63", name: "Philippines", flag: "PH" },
  { code: "+48", name: "Poland", flag: "PL" },
  { code: "+351", name: "Portugal", flag: "PT" },
  { code: "+1 787", name: "Puerto Rico", flag: "PR" },
  { code: "+974", name: "Qatar", flag: "QA" },
  { code: "+262", name: "Reunion", flag: "RE" },
  { code: "+40", name: "Romania", flag: "RO" },
  { code: "+7", name: "Russia", flag: "RU" },
  { code: "+250", name: "Rwanda", flag: "RW" },
  { code: "+685", name: "Samoa", flag: "WS" },
  { code: "+378", name: "San Marino", flag: "SM" },
  { code: "+966", name: "Saudi Arabia", flag: "SA" },
  { code: "+221", name: "Senegal", flag: "SN" },
  { code: "+381", name: "Serbia", flag: "RS" },
  { code: "+248", name: "Seychelles", flag: "SC" },
  { code: "+232", name: "Sierra Leone", flag: "SL" },
  { code: "+65", name: "Singapore", flag: "SG" },
  { code: "+421", name: "Slovakia", flag: "SK" },
  { code: "+386", name: "Slovenia", flag: "SI" },
  { code: "+677", name: "Solomon Islands", flag: "SB" },
  { code: "+27", name: "South Africa", flag: "ZA" },
  {
    code: "+500",
    name: "South Georgia and the South Sandwich Islands",
    flag: "GS",
  },
  { code: "+82", name: "South Korea", flag: "KR" },
  { code: "+34", name: "Spain", flag: "ES" },
  { code: "+94", name: "Sri Lanka", flag: "LK" },
  { code: "+249", name: "Sudan", flag: "SD" },
  { code: "+597", name: "Suriname", flag: "SR" },
  { code: "+268", name: "Swaziland", flag: "SZ" },
  { code: "+46", name: "Sweden", flag: "SE" },
  { code: "+41", name: "Switzerland", flag: "CH" },
  { code: "+963", name: "Syria", flag: "SY" },
  { code: "+886", name: "Taiwan", flag: "TW" },
  { code: "+992", name: "Tajikistan", flag: "TJ" },
  { code: "+255", name: "Tanzania", flag: "TZ" },
  { code: "+66", name: "Thailand", flag: "TH" },
  { code: "+670", name: "Timor Leste", flag: "TL" },
  { code: "+228", name: "Togo", flag: "TG" },
  { code: "+690", name: "Tokelau", flag: "TK" },
  { code: "+676", name: "Tonga", flag: "TO" },
  { code: "+1 868", name: "Trinidad and Tobago", flag: "TT" },
  { code: "+216", name: "Tunisia", flag: "TN" },
  { code: "+90", name: "Turkey", flag: "TR" },
  { code: "+993", name: "Turkmenistan", flag: "TM" },
  { code: "+1 649", name: "Turks and Caicos Islands", flag: "TC" },
  { code: "+688", name: "Tuvalu", flag: "TV" },
  { code: "+1 340", name: "U.S. Virgin Islands", flag: "VI" },
  { code: "+256", name: "Uganda", flag: "UG" },
  { code: "+380", name: "Ukraine", flag: "UA" },
  { code: "+971", name: "United Arab Emirates", flag: "AE" },
  { code: "+44", name: "United Kingdom", flag: "GB" },
  { code: "+1", name: "United States", flag: "US" },
  { code: "+598", name: "Uruguay", flag: "UY" },
  { code: "+998", name: "Uzbekistan", flag: "UZ" },
  { code: "+678", name: "Vanuatu", flag: "VU" },
  { code: "+58", name: "Venezuela", flag: "VE" },
  { code: "+84", name: "Vietnam", flag: "VN" },
  { code: "+681", name: "Wallis and Futuna", flag: "WF" },
  { code: "+967", name: "Yemen", flag: "YE" },
  { code: "+260", name: "Zambia", flag: "ZM" },
  { code: "+263", name: "Zimbabwe", flag: "ZW" },
];
