export { SettingsPage } from "./SettingsPage";
export { AccountPage } from "./AccountPage/AccountPage";
export { CommunityPage } from "./CommunityPage/CommunityPage";
export { HelpPage } from "./HelpPage/HelpPage";
export { LanguagePage } from "./LanguagePage/LanguagePage";
export { LegalPage } from "./LegalPage/LegalPage";
export { NotificationsPage } from "./NotificationsPage/NotificationsPage";
export { PrivacyPage } from "./PrivacyPage/PrivacyPage";
export { AboutPage } from "./AboutPage/AboutPage";
